### ISSUE TITLE
prompt か negative promptを空欄にした時、KeyErrorになる

### ISSUE THREAD

**Issue by Hamken100per** [shingo1228/ComfyUI-send-eagle-slim#1]
prompt、もしくは negative promptを空欄にして生成した画像を保存する時に、KeyErrorになります。

prompt_info_extractor.py の gather_info() の以下のところです。

> "prompt": prompt_text["prompt"],
> "negative": prompt_text["negative"],

**Comment by shingo1228** [comment]
確認ありがとうございます。また、返信遅くなりました。
Keyチェックを追加して、prompt、negative promtが空欄、若しくはワークフローの構成により、それらが取得できなかった場合にも対応しました。
ご確認頂けると幸いです。
